### ISSUE TITLE
MIME Alias Support

### ISSUE THREAD

**Issue by sanzeeb3** [awesomemotive/file-upload-types#16]
Currently, WordPress doesn't allow multiple mime types for a single extension. It would be nice to support alias, though.

References:

- https://core.trac.wordpress.org/ticket/40175
- https://core.trac.wordpress.org/ticket/39963

- https://wordpress.stackexchange.com/a/323757/126847

**Comment by jaredatch** [comment]
Not sure how hard it will be to accomplish this, but some of those work arounnds in the trac tickets/SO snippets look promising.

Needless to say if we are able to add alias support, that will be huge and solve a massive pain point for users.

If we can add support for this that means we can allow comma separated mime types or multiple custom items with different mime types for the same file extension.

Also, then we could update the default extensions we ship to include common variations. Looks like in the trac ticket that work has already been done and there's a nice list compiled with common aliases.

When time allows, please proceed to do some research on this. Once you have some thoughts, let's figure out next possible steps :)

**Comment by sanzeeb3** [comment]
Supporting multiple mime types for a single extension looks pretty much accomplishable. Easiest is to allow with comma-separated mime types. Multiple custom items with different mime types for the same file extension may not be an organized way. 

Updating the list of current file types with all the aliases mimes will be nice. We'll need to check for each of the types we currently have because if a file type has already been enabled, it's mime type is compared from the current list and only extension is stored in the database. If the existing user already has a type enabled, all the added aliases should also be allowed now with the change? I'm assuming a group of mime types for a given extension is supposed to be checked once and we're not allowing to check each aliases separately for a single extension. Something like this: https://a.supportally.com/eRYqYR.

The question is also for the default WordPress allowed mime types. Since we don't have them in the available list. Should we attempt to support their alias by default or let users explicitly override using custom types?

**Comment by jaredatch** [comment]
@sanzeeb3 Sounds very promising!

For best security, we should not make any changes to whatever the user has active before these changes.

By that I mean if they are already added support for `.ai` files, we should not auto apply the MIME aliases for this file automatically after upgrading.

While you could argue that it's helpful for many (and I would agree), I don't think we should potentially make changes to the files allowed on their site on the upgrade. There could be a case where due to security purposes the site admin only wants to allow the single primary MIME type for `.ai`. We just don't know.

As far as the design adjustments to support multiple MIME types for an extension, that's a good question. Can you let me know how many file extensions we ship that we would potentially have aliases from (I think it's in one of those trac tickets or existing plugin linked from there)? 

Because our design decisions might be different depending on how many default file extensions we would include aliases for. Once we know this, I can loop in Matt and we can get him involved.

Let me know :)

**Comment by sanzeeb3** [comment]
@jaredatch with reference to [this list of mimes](https://core.trac.wordpress.org/attachment/ticket/39963/media-mimes.php), around 1/3rd of our current list of extensions have aliases. I've checked first 60 extensions out of which 20 have aliases.

**Comment by sanzeeb3** [comment]
oh, I checked that manually. :) To be exact, 272 out of current 690 extensions have aliases.

**Comment by jaredatch** [comment]
Thank you for manually checking, I appreciate it - good to know. I'll get with @mattbrett on this and keep you in the loop :)

**Comment by jaredatch** [comment]
@sanzeeb3 Matt has it on his short list to look at this from design point of view.

As far as actual implementation, you're good to work on it as time allows :)

**Comment by mattbrett** [comment]
This is an easy change. The line-height is already good for multiple lines, so easiest thing to do would be to add additional MIME types with a `<br>` between.

![wpforms-dev test_wp-admin_options-general php_page=file-upload-types](https://user-images.githubusercontent.com/868109/88963522-cf011400-d25c-11ea-8f50-b7954204a804.png)

**Comment by jaredatch** [comment]
@mattbrett would it be better top top align these or keep them middle aligned?

**Comment by sanzeeb3** [comment]
@jaredatch so, we have a group of all mime types for a single extension and a single checkbox to allow all at once. Yet, we don't allow aliases for previous users upgrading to this version, and the future users won't have the control to manage the primary and aliases. Now if the previous users want to support the aliases, they'll need to just save the settings? or we might need two separate checkboxes for primary and all of it's aliases for some kind of granular control.

**Comment by mattbrett** [comment]
> @mattbrett would it be better top top align these or keep them middle aligned?

Yeah, that looks better.

@sanzeeb3 Please also add `vertical-align: top;` to **#file-upload-types .file-upload-types-content .file-upload-types-table .table-container td**.

**Comment by jaredatch** [comment]
Great questions @sanzeeb3 - I've looked at this deeper (thanks for your patience on this).

I tend to think we should avoid having granular controls, because I think that is going to get tricky.

Most users won't know the difference between primary and alias MIME types. I suspect there will be multiple instances where that will be a gray area even for us, given there is not always going to be an "official" MIME type for a file extension. For example with AI files, it seems there are at least two popular/common MIME types - I'm not sure how we make the call what is primary and what is an alias.

So I think it has potential to just add friction and confusion to end users, who ultimately just want to be able to have the file uploaded, and very likely don't even know what a MIME type is.

I think a good approach to consider would be:
- New installs get alias support automatically.
- Existing/previous installs get current support, with ability to opt-in to alias support.

To do this, we could create `file-types-list-v2.json` (or similar), which supports aliases. New installs use this.

Previous installs continue to use the existing `file-types-list.json`. When the settings page is opened, at the top we display a notice, see https://a.cl.ly/wbu7mwA0

From this notice, user can:
- Dismiss (`(x)`)
- Enable support
- Learn more, which will take them to new section in our doc about multiple mime type support

After enabling multiple mime types, we can them know they need to resave their settings (which I assume will be needed), see https://a.cl.ly/v1u2rbe1

As far as detection on this, we'll have to see the best approach. Perhaps it's as easy is seeing if the `file_upload_types` option already exists (previous install) or not (new install).

Lastly, if multiple mimetype support is present, we'll want to change the place holder (https://a.cl.ly/E0unqY9d) to `MIME Types, comma separated` to make it obvious that that can be done.

Let me know if you have any questions :)

**Comment by jaredatch** [comment]
Another thing we'll need to decide is if multiple MIME types are stored as comma separated or as an array. I don't have a preference, just something I thought of!

**Comment by sanzeeb3** [comment]
@jaredatch If there's no preference, I'd go with storing multiple MIME types in an array. and accept multiple mime-types both by comma-separated and using the + icon with same extension. question is the notice for old installs should dismiss forever or reappear on another page load when clicking on Dismiss ((x))?

**Comment by jaredatch** [comment]
I think we if we offer dismiss it should be forever or simply don't include it the dismiss button at all.

The argument can be made both ways - to offer dismiss option or not.

As the maintainer, do you have an opinion or preference?

**Comment by sanzeeb3** [comment]
Yeah, that is opinion based. imo, It's better to not offer dismiss button at all. If there's a dismiss button, I think more will dismiss (just like any other WordPress notice) rather than enable multiple types. If there's no dismiss, users will think before enabling. 

> After enabling multiple mime types, we can them know they need to resave their settings (which I assume will be needed), see https://a.cl.ly/v1u2rbe1

They will not need to resave the settings. Only extensions are stored in the database, mime type for the stored extension is used from the list directly. If they enable, start using from the `file-upload-types-v2.json`.

**Comment by jaredatch** [comment]
Closing since this has been merged.

**Comment by slaFFik** [comment]
I haven't merged this manually, because currently `master` branch is the main one, while all the developers and PRs are done against `develop` branch. So when `develop` would be merged into `master` - this issue would be closed automatically.

@jaredatch Perhaps we need to change the main branch in this repo to `develop` as well, so it will be the same as in `wpforms-plugin` and `wp-mail-smtp-plugin` repo.

**Comment by sanzeeb3** [comment]
There's a link to be updated.

> Learn more, which will take them to new section in our doc about multiple mime type support

@jessquig @nicolemagerko can we anticipate what the link to the new section would be? The docs should also be updated before (or simultaneously with) the release.

**Comment by nicolemagerko** [comment]
@sanzeeb3 Sure! So looking at the doc as it currently is, I'm thinking the best way to do this would be to add another section under the "Adding More File Upload Types", which means the URL would probably only need to anchor to that section. Right now I think that `#multiple-mime-types` would be the best, meaning the entire URL would be `https://wpforms.com/docs/how-to-allow-additional-file-upload-types/#multiple-mime-types`.

@jessquig So the ToC would end up being:

- File Types Allowed By Default

- Adding More File Upload Types
           - Preset Options
           - Adding Custom Types
           - Allowing Multiple MIME Types
etc., what do you think?

**Comment by jaredatch** [comment]
@slaFFik Good call, I've changed default branch to `develop` to make things consistent.

**Comment by sanzeeb3** [comment]
@nicolemagerko sounds good, thanks. v1.2.0 update is planned for the next week. If we can update the doc anytime next week, I'd go with the release.
