### ISSUE TITLE
Improve tooltip text

### ISSUE THREAD

**Issue by sanzeeb3** [awesomemotive/file-upload-types#23]
Current tooltip text is not helpful at all. There's the same 'Add custom file types' text in the tooltip. It might be more helpful if we link the mime type checker services like [this](https://htmlstrip.com/mime-file-type-checker) or direct to our documentation.

![Screenshot on 2020-08-29 at 17_33_42](https://user-images.githubusercontent.com/16817248/91636136-eda22880-ea1d-11ea-910f-b80d75a7e070.png)

**Comment by sanzeeb3** [comment]
@jessquig @jaredatch, could you please provide some feedback on this?

**Comment by jessquig** [comment]
I totally agree with you that this needs to be better @sanzeeb3. I'd like it to link to https://wpforms.com/docs/how-to-allow-additional-file-upload-types/ -- but could you please look at that doc and see if we've included the level of detail that would be helpful in this tooltip?

In other words, I want to link to this doc. But I want to also make sure that we edit this doc however is needed so that it's relevant and helpful to anyone checking out this tooltip :) 

Nicole's actually just been working on edits to this doc (currently waiting on me to review), so here's her draft: https://wpforms.com/?p=973604&post_type=wpforms_doc&preview=1&_ppp=a6b1743349

**Comment by sanzeeb3** [comment]
@jessquig yes, the doc contains all the required details. A link to the section (#custom-types) of the doc might be helpful. But, we already have the 'View Documentation' button,'Learn More' link pointing to this doc. I prefer a minimal concise description in the tooltip instead of the link. Something like:

> Enter the description, MIME type, and extension of the file. Multiple MIME types for a single extension can be separated by a comma.

**Comment by sanzeeb3** [comment]
With this, the placeholder text `MIME Types, comma separated` is not necessary because it could be confusing to most users even though helpful for a few. also multiple mimes for a single extension can be entered via + which can be more standard way.
