### ISSUE TITLE
Unable to upload .stp or .step files

### ISSUE THREAD

**Issue by lonesomewalker** [awesomemotive/file-upload-types#70]
Even after manually adding them, and chosing the right mime type... not working :-(

**Comment by kkarpieszuk** [comment]
Hello @lonesomewalker I am sorry you have troubles. 

The problem is known and in general it is incorrect mime type. The mime type for the file which you find on the internet does not have to be the same one your server is using to match the file, please see the issue #53 

We are going to make mime type recognition more "intelligent". For the time being please try a different mime types. For stp file please try `application/STEP`, `application/step`, `application/stp`, `text/plain`, `model/step` or `application/octet-stream`

**Comment by lonesomewalker** [comment]
I mean i can manipulate the mimetypes on server side, full access to this :-)

**Comment by kkarpieszuk** [comment]
@lonesomewalker oh, that's good. please set then the same mime type on the server and in the plugin and it should work. 

please be careful: please read the whole opening post for #53 as I found mime type returned by CLI tools on the server can be different on the same server than returned by PHP functions (if you look into PHP interpreter source code you will see they decided for their own logic to recognize mime type, independent from server tools). at the bottom of the opening ticket there is PHP script which you should run to check the mime type on the server, returned by PHP functions.

**Comment by omarfarooq86** [comment]
https://secure.helpscout.net/conversation/2380750245/3600903/ .stp couldn't be added using the plugin however using the https://wordpress.org/plugins/enhanced-media-library/ I could add using same MIME information
