### ISSUE TITLE
Update File Upload Types to support latest WP core version

### ISSUE THREAD

**Issue by joannafoss** [awesomemotive/file-upload-types#71]
## Description
Update the plugin to support latest WP core version. A customer reported that there is a notice on the plugin page alerting that the plugin has not been tested with the past 3 versions of WordPress. 

Customer report: https://wordpress.org/support/topic/ouch-no-plugin-updates/
Slack conversation: https://awesomemotive.slack.com/archives/CG9N6KL4B/p1718209041296829

**Comment by kkarpieszuk** [comment]
@joannafoss I would like to ask for the scope of this task: is this just a matter to update this version number or - in the span of this task - we want also to have this released?

updating the number would be super easy, just a one line change. but to have this delivered to the customer, we need also:

- test if we are really still compatible
- prepare a new version of the plugin (update its version number too, build)
- send it to wp.org svn server


and if we are going to release a new version it could be good to have something else included, not just numbers (ane if we are going to include anything, I really vote for https://github.com/awesomemotive/file-upload-types/pull/64 which will fix great number of reported issues)

I am asking all those questions because FUT plugin is not maintained in the same way as WPForms: we basically don't have procedures here and we return to this plugin only once in a year or less as you can see :)

**Comment by joannafoss** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WPForms-A-Team-62a0f11261858e0018a7a619/issues/awesomemotive/file-upload-types/71?planning-poker) with Zenhub @kkarpieszuk
