### ISSUE TITLE
File Upload Types design changes

### ISSUE THREAD

**Issue by kkarpieszuk** [awesomemotive/file-upload-types#75]
In this comment https://github.com/awesomemotive/file-upload-types/issues/53#issuecomment-1496729473 @mattbrett suggested how defining file type by sample should look and behave, but he also provided a bit deeper interface redesign. This ticket is to handle the redesign part and not block File By Sample functionality (which is handled in #64 )

Figma file: https://www.figma.com/design/ML5HOsdI9xsVZNEPHkGybY/File-Upload-Types?node-id=0-1&t=zawMaVMDwZ6XQ58V-0

Screencast: https://a.supportally.com/v/xhxCgt

**Comment by kkarpieszuk** [comment]
I think this is also opportunity to add UTM params to the links in sidebar of File Upload Types plugin Settings screen:

![image](https://github.com/awesomemotive/file-upload-types/assets/2388617/fe1dbe10-eb36-49cc-a02d-9ce3ffed89a6)

For time being we have none. 

@joannafoss I added to each link from the screenshot (and each link redirect to mail page of the plugin pro, https://wpforms.com etc) those params:

```
?utm_source=WordPress&utm_medium=settings-sidebar&utm_campaign=file-upload-types
```

so the links are (respectively to the screenshot):

https://wpforms.com?utm_source=WordPress&utm_medium=settings-sidebar&utm_campaign=file-upload-types

https://wpmailsmtp.com?utm_source=WordPress&utm_medium=settings-sidebar&utm_campaign=file-upload-types

https://sendlayer.com?utm_source=WordPress&utm_medium=settings-sidebar&utm_campaign=file-upload-types

https://aioseo.com?utm_source=WordPress&utm_medium=settings-sidebar&utm_campaign=file-upload-types

Could you check with content team if they are ok?

**Comment by joannafoss** [comment]
@erickfogtman can you please review Konrad's UTM params in [the comment above](https://github.com/awesomemotive/file-upload-types/issues/75#issuecomment-2214007458)?

**Comment by erickfogtman** [comment]
Hey @joannafoss thanks for tagging me.

@kkarpieszuk your recommendations are great but I refined them a bit more. Mainly because I think `settings-sidebar` can be confused as coming from the main plugin (WPF, SMTP, etc.). I also added `utm_content`.

```
?utm_source=WordPress&utm_medium=fut-recommendations&utm_campaign=file-upload-types&utm_content=get-[plugin_name]
```

So for each plugin, it would be:

- WPForms: `utm_source=WordPress&utm_medium=fut-recommendations&utm_campaign=file-upload-types&utm_content=get-wpforms`
- WP Mail SMTP: `utm_source=WordPress&utm_medium=fut-recommendations&utm_campaign=file-upload-types&utm_content=get-wp-mail-smtp`
- SendLayer: `utm_source=WordPress&utm_medium=fut-recommendations&utm_campaign=file-upload-types&utm_content=get-sendlayer`
- All in One SEO: `utm_source=WordPress&utm_medium=fut-recommendations&utm_campaign=file-upload-types&utm_content=get-aioseo`

Now my question is, do we have any other links in this plugin that we should add UTMs to? Happy to provide those as well :).

**Comment by kkarpieszuk** [comment]
thank you @erickfogtman ! done

**Comment by joannafoss** [comment]
@kkarpieszuk per Erick's question, are there any other links that need utm params?

**Comment by kkarpieszuk** [comment]
In fact, there is one more, the button in top right corner View Documentation:

![image](https://github.com/user-attachments/assets/96500c26-4045-4f9a-a182-6c145179e422)

Redirects to not parametrized yet https://wpforms.com/docs/how-to-allow-additional-file-upload-types/ URL

**Comment by joannafoss** [comment]
@erickfogtman please see above. 👀

**Comment by erickfogtman** [comment]
For the `View Documentation` button, let's go with

`utm_source=WordPress&utm_medium=fut-help&utm_campaign=file-upload-types&utm_content=view-documentation`

@kkarpieszuk @joannafoss

**Comment by kkarpieszuk** [comment]
Thank you @erickfogtman , applied
